### ISSUE TITLE
postData.map is not a function

### ISSUE THREAD

**Issue by outdatedx** [vercel/next-learn#55]
Not sure if this is the right place to ask it but I saw the example here so why not,

So I'm learning next rn and I facing a issue where I cant display the images from the .md file I have

I was following through the  guide and then I wanted to do something else as well ( The SSG blog Guide )
I saw they way they were able to display all the blogs in the certain folder using 
```
{allPostsData.map(({ id, title }) => (
            <li className="{utilStyles.listItem}" key={id}>
                  <a href={`projects/${id}`}>{title}</a>
            </li>
            ))}
```
But I want to do the same for the blog its self but instead for images 
work.md
```
---
title: work_2 test 2021
Projects:
  - type: Image
    photo: assets/images/cv.png
  - photo: assets/images/e1hjoxfxsaayvjh.jpg
---

```

https://pastebin.com/raw/CPGjCKbY and this is what I came up with but it gives me a error saying postData.map is not a function 
can anyone help me with this 

Oh also I'm using netlifycms to generate these .md if that helps.
